<?php
 defined('BASEPATH') OR exit('No direct script access allowed');
class Email extends CI_Controller{
    function __construct(){
        parent::__construct();
        $this->load->library('MyPHPMailer'); // load library
        $this->load->model('invoice_model');

    	$config = Array(
			'protocol'		=> 'smtp',
			'smtp_host' 	=> 'ssl://smtp.googlemail.com',
			'smtp_port' 	=> 465,
			'smtp_user' 	=> 'rindra.yudha@gmail.com',	// prisiliadecoration@gmail.com
			'smtp_pass' 	=> 'r1ndr40t0n6',	// prisilia1234
			'mailtype' 		=> 'html'
		);
		$this->load->library('email', $config);
    }
 
    function emailSend(){
        $fromEmail = "rindra.yudha@gmail.com"; //ganti dg alamat email kamu di sini. budianatekom@gmail.com
        //$isiEmail = "Isi email tulis disini"; //ini isi emailnya
		$nm_cust="nama customer";
		$no_inv="nomor invoice";
		$number_terbilang="jumlah terbilang";
		$jatuh_tempo="tanggal jatuh tempo";
		$ups = "up";
		$saldo_akhir="jumlah angka";
		$isiEmail = "<html>
					<body style=\"font-family:Verdana, Geneva, sans-serif; font-size:12px; color:#666666;\">
					
					<p>Kepada <b>".$nm_cust."</b></p>
					<p>Perihal : Pemberitahuan ke - 1</p>
					<p>UP : ".$ups."</p>
					<p>Dengan Hormat,</p>
					<p>Dengan ini kami memberitahukan kepada Bapak/Ibu bahwa Invoice No. <b> ".$no_inv." </b> sebesar <b>Rp. ".number_format($saldo_akhir)." </b><i>(".$number_terbilang.")</i> akan jatuh tempo pada tanggal <b>".date('d-m-Y', strtotime($jatuh_tempo)).".</b></p>
					<p>Silahkan lakukan pembayaran sebelum tanggal jatuh tempo untuk menghindari denda keterlambatan, dan abaikan email ini jika Bapak/Ibu telah melakukan pembayaran.</p>
					<p>Atas perhatian dan kerjasamanya, kami ucapkan terima kasih.</p>
					<br/>
					<p>Hormat Kami,</p>
					<br/>
					<p>Pisilia Decoration</p>
					</body>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
					
					<hr>
					<body style=\"font-family:Verdana, Geneva, sans-serif; font-size:10px; color:#666666;\">
					<p>This Document is automatic generated by system</p>
					<p>No signature required</p>
					</body>
					<hr>

				</html>";
        $mail = new PHPMailer();
        $mail->IsHTML(true);    //ini agar email bisa mengirim dalam format HTML
        $mail->IsSMTP();   //kita akan menggunakan SMTP
        $mail->SMTPAuth   = true; //Autentikasi SMTP: enabled
        $mail->SMTPSecure = "ssl";  //jenis keamanan SMTP
        $mail->Host       = "smtp.gmail.com"; //setting GMail sebagai SMTP server
        $mail->Port       = 465; // SMTP port to connect to GMail
        $mail->Username   = $fromEmail;
        $mail->Password   = "r1ndr40t0n6"; //ganti dg password GMail kamu.	buniwangi12
        $mail->SetFrom('rindra.yudha@gmail.com', 'noreply');  //Siapa yg mengirim email.	budianatekom@gmail.com
        $mail->Subject    = "Subjek email"; //ini subjek emailnya
        $mail->Body       = $isiEmail;
        $toEmail = "rindra.yudha@gmail.com"; // siapa yg menerima email ini.	budiana.app@gmail.com
        $mail->AddAddress($toEmail);
       
        if(!$mail->Send()) {
            echo "Eror: ".$mail->ErrorInfo;
        } else {
            echo "Email berhasil dikirim";
        }
    }

    function view_mail_schedule_invoice(){
    	$owner		= $this->db->query("SELECT * FROM dk_master_owner LIMIT 1")->row();
    	$schedule	= $this->invoice_model->q_schedule_invoice_tomorrow2();	// q_schedule_invoice_tomorrow()
    	$data	= array(
    		'company'	=> $owner,
    		'schedule'	=> $schedule
    	);
    	$this->load->view('invoicing/mail_schedule_invoice', $data);	// invoicing/mail_schedule_invoice
    }

    function send_mail_schedule_invoice(){
    	$owner		= $this->db->query("SELECT * FROM dk_master_owner LIMIT 1")->row();
    	$schedule	= $this->invoice_model->q_schedule_invoice_tomorrow2();	//q_schedule_invoice_tomorrow()

    	$this->email->set_mailtype('html');
		$this->email->from('rindra.yudha@gmail.com', 'Pisilia Decoration');	// 'prisiliadecoration@gmail.com', 'Prisilia Decoration'
		$this->email->subject($owner->nama.' - '.'Pemberitahun Jadwal Jatuh Tempo (tes email reminder');
		$this->email->to('rindra.yudha@gmail.com');	//$owner->email1
		$this->email->cc('hadikusyanto@gmail.com');	//frankysaputra83@gmail.com

		if ($schedule > 0) {
			$data	= array(
	    		'company'	=> $owner,
	    		'schedule'	=> $schedule
	    	);

	    	$body	= $this->load->view('invoicing/mail_schedule_invoice.php', $data, TRUE);	// invoicing/mail_schedule_invoice.php
			$this->email->message($body);
			$this->email->set_newline("\r\n");

			if ($this->email->send()) {
				echo "Email Berhasil Terkirim!!";
			} else {
				echo "Email Gagal Terkirim!!";
			}
    	} else {
    		echo "Tidak ada jadwal invoice besok!!";
    	}
    }
}
?>