<?php
defined('BASEPATH') or exit('No direct script access allowed');
class Email extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		//$this->load->library('MyPHPMailer'); // load library
		$this->load->model('invoice_model');

		// $config = array(
		// 	'protocol'		=> 'smtp',
		// 	'smtp_host' 	=> 'tls://smtp.gmail.com', // ssl://smtp.googlemail.com
		// 	'smtp_port' 	=> 587, // 465
		// 	'smtp_user' 	=> 'rindra.yudha@gmail.com',	// prisiliadecoration@gmail.com
		// 	'smtp_pass' 	=> '',	// prisilia1234
		// 	'mailtype' 		=> 'html'
		// );
		// $this->load->library('email', $config);
	}

	function tes_kirim()
	{
		$nm_cust = "nama customer";
		$no_inv = "nomor invoice";
		$number_terbilang = "jumlah terbilang";
		$jatuh_tempo = "tanggal jatuh tempo";
		$ups = "up";
		$saldo_akhir = "1000000";
		$isiEmail = "<html>
					<body style=\"font-family:Verdana, Geneva, sans-serif; font-size:12px; color:#666666;\">
					
					<p>Kepada <b>" . $nm_cust . "</b></p>
					<p>Perihal : Pemberitahuan ke - 1</p>
					<p>UP : " . $ups . "</p>
					<p>Dengan Hormat,</p>
					<p>Dengan ini kami memberitahukan kepada Bapak/Ibu bahwa Invoice No. <b> " . $no_inv . " </b> sebesar <b>Rp. " . number_format($saldo_akhir) . " </b><i>(" . $number_terbilang . ")</i> akan jatuh tempo pada tanggal <b>" . date('d-m-Y', strtotime($jatuh_tempo)) . ".</b></p>
					<p>Silahkan lakukan pembayaran sebelum tanggal jatuh tempo untuk menghindari denda keterlambatan, dan abaikan email ini jika Bapak/Ibu telah melakukan pembayaran.</p>
					<p>Atas perhatian dan kerjasamanya, kami ucapkan terima kasih.</p>
					<br/>
					<p>Hormat Kami,</p>
					<br/>
					<p>Pisilia Decoration</p>
					</body>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
					
					<hr>
					<body style=\"font-family:Verdana, Geneva, sans-serif; font-size:10px; color:#666666;\">
					<p>This Document is automatic generated by system</p>
					<p>No signature required</p>
					</body>
					<hr>

				</html>";
		$mail = new PHPMailer();

		//Tell PHPMailer to use SMTP
		$mail->isSMTP();

		//Enable SMTP debugging
		// SMTP::DEBUG_OFF = off (for production use)
		// SMTP::DEBUG_CLIENT = client messages
		// SMTP::DEBUG_SERVER = client and server messages
		$mail->SMTPDebug = SMTP::DEBUG_SERVER;

		//Set the hostname of the mail server
		$mail->Host = 'smtp.gmail.com';
		// use
		// $mail->Host = gethostbyname('smtp.gmail.com');
		// if your network does not support SMTP over IPv6

		//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
		$mail->Port = 587;

		//Set the encryption mechanism to use - STARTTLS or SMTPS
		// $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
		$mail->SMTPSecure = 'tls';

		//Whether to use SMTP authentication
		$mail->SMTPAuth = true;

		//Username to use for SMTP authentication - use full email address for gmail
		$mail->Username = 'rindra.yudha@gmail.com';

		//Password to use for SMTP authentication
		$mail->Password = '';

		//Set who the message is to be sent from
		$mail->setFrom('rindra.yudha@gmail.com', 'Pengirim');

		//Set an alternative reply-to address
		//$mail->addReplyTo('replyto@example.com', 'Penerima');

		//Set who the message is to be sent to
		$mail->addAddress('rindra.yudha@gmail.com', 'John Doe');

		//Set the subject line
		$mail->Subject = 'PHPMailer GMail SMTP test';
		$mail->Body       = $isiEmail;
		//Read an HTML message body from an external file, convert referenced images to embedded,
		//convert HTML into a basic plain-text alternative body
		//$mail->msgHTML(file_get_contents('contents.html'), __DIR__);

		//Replace the plain text body with one created manually
		$mail->AltBody = 'This is a plain-text message body';

		//Attach an image file
		//$mail->addAttachment('images/phpmailer_mini.png');

		//send the message, check for errors
		if (!$mail->send()) {
			echo 'Mailer Error: ' . $mail->ErrorInfo;
		} else {
			echo 'Message sent!';
			//Section 2: IMAP
			//Uncomment these to save your message in the 'Sent Mail' folder.
			#if (save_mail($mail)) {
			#    echo "Message saved!";
			#}
		}
	}

	function save_mail($mail)
	{
		//You can change 'Sent Mail' to any other folder or tag
		$path = '{imap.gmail.com:993/imap/ssl}[Gmail]/Sent Mail';

		//Tell your server to open an IMAP connection using the same username and password as you used for SMTP
		$imapStream = imap_open($path, $mail->Username, $mail->Password);

		$result = imap_append($imapStream, $path, $mail->getSentMIMEMessage());
		imap_close($imapStream);

		return $result;
	}

	function emailSend()
	{
		// $this->load->library('MyPHPMailer');
		$sroot = $_SERVER['DOCUMENT_ROOT'];
		include "$sroot/gl/application/libraries/PHPMailer/PHPMailerAutoload.php";
		// echo "$sroot/application/libraries/PHPMailer/PHPMailerAutoload.php";

		$fromEmail = "test@dutastudy.com"; //ganti dg alamat email kamu di sini. budianatekom@gmail.com
		//$isiEmail = "Isi email tulis disini"; //ini isi emailnya
		$nm_cust = "nama customer";
		$no_inv = "nomor invoice";
		$number_terbilang = "jumlah terbilang";
		$jatuh_tempo = "tanggal jatuh tempo";
		$ups = "up";
		$saldo_akhir = "1000000";
		$Body = "<html>
					<body style=\"font-family:Verdana, Geneva, sans-serif; font-size:12px; color:#666666;\">
					
					<p>Kepada <b>" . $nm_cust . "</b></p>
					<p>Perihal : Pemberitahuan ke - 1</p>
					<p>UP : " . $ups . "</p>
					<p>Dengan Hormat,</p>
					<p>Dengan ini kami memberitahukan kepada Bapak/Ibu bahwa Invoice No. <b> " . $no_inv . " </b> sebesar <b>Rp. " . number_format($saldo_akhir) . " </b><i>(" . $number_terbilang . ")</i> akan jatuh tempo pada tanggal <b>" . date('d-m-Y', strtotime($jatuh_tempo)) . ".</b></p>
					<p>Silahkan lakukan pembayaran sebelum tanggal jatuh tempo untuk menghindari denda keterlambatan, dan abaikan email ini jika Bapak/Ibu telah melakukan pembayaran.</p>
					<p>Atas perhatian dan kerjasamanya, kami ucapkan terima kasih.</p>
					<br/>
					<p>Hormat Kami,</p>
					<br/>
					<p>Pisilia Decoration</p>
					</body>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
					
					<hr>
					<body style=\"font-family:Verdana, Geneva, sans-serif; font-size:10px; color:#666666;\">
					<p>This Document is automatic generated by system</p>
					<p>No signature required</p>
					</body>
					<hr>

				</html>";
		/*
	$mail = new PHPMailer();
		$mail->IsHTML(true);    //ini agar email bisa mengirim dalam format HTML
		$mail->IsSMTP();   //kita akan menggunakan SMTP
		$mail->MailerSMTP = "smtp";
		$mail->SMTPAuth   = true; //Autentikasi SMTP: enabled
		$mail->SMTPSecure = "ssl";  //jenis keamanan SMTP
		$mail->Host       = "surat.agungrent.co.id"; //setting GMail sebagai SMTP server
		$mail->Port       = 587; // SMTP port to connect to GMail
		$mail->Username   = "info@agungrent.co.id";
		$mail->Password   = "misAsT##!!"; //ganti dg password GMail kamu.	buniwangi12
		$mail->SetFrom('info@agungrent.co.id', 'pengirim');  //Siapa yg mengirim email.	budianatekom@gmail.com
		$mail->Subject    = "Subjek email"; //ini subjek emailnya
		$mail->Body       = $isiEmail;
		$toEmail = "rindra.yudha@gmail.com"; // siapa yg menerima email ini.	budiana.app@gmail.com
		$mail->AddAddress($toEmail);

		if (!$mail->Send()) {
			echo "MASIH GAK BISA: " . $mail->ErrorInfo;
		} else {
			echo "Email berhasil dikirim";
		}

*/


		$mail					= new PHPMailer();

		$mail->IsSMTP();
		$mail->Mailer			= "smtp";
		$mail->Host			= "surat.agungrent.co.id";
		$mail->Port			= "587";
		$mail->SMTPAuth			= true;
		$mail->Username			= "info@agungrent.co.id";
		$mail->Password			= "misAsT##!!";

		// - - - - - - - - - - - - - - - - - - - From - To - - - - - - - - - - - - - - - - - - - //


		$mail->From				= 'info@agungrent.co.id'; // sender email
		$mail->FromName				= 'Info Agungrent'; // name sender
		$Email_To = 'hadikusyanto@gmail.com';
		$Email_Name = 'info@agungrent.co.id';


		$mail->AddAddress($Email_To, ucwords(strtolower($Email_Name)));

		$mail->addCC('mahrus.ali@agungrent.co.id', 'Mahrus Ali');

		// - - - - - - - - - - - - - - - - - - - Message Here - - - - - - - - - - - - - - - - - - - //
		$mail->IsHTML(true);
		$mail->Subject	= "Informasi Asuransi";

		$mail->Body		= $Body;


		if (!$mail->Send()) {
			echo "MASIH GAK BISA: " . $mail->ErrorInfo;
		} else {
			echo "Email berhasil dikirim";
		}
	}

	function view_mail_schedule_invoice()
	{
		$owner		= $this->db->query("SELECT * FROM dk_master_owner LIMIT 1")->row();
		$schedule	= $this->invoice_model->q_schedule_invoice_tomorrow2();	// q_schedule_invoice_tomorrow()
		$data	= array(
			'company'	=> $owner,
			'schedule'	=> $schedule
		);
		$this->load->view('invoicing/mail_schedule_invoice', $data);	// invoicing/mail_schedule_invoice
	}

	function send_mail_schedule_invoice()
	{
		$owner		= $this->db->query("SELECT * FROM dk_master_owner LIMIT 1")->row();
		$schedule	= $this->invoice_model->q_schedule_invoice_tomorrow2();	//q_schedule_invoice_tomorrow()

		$this->email->set_mailtype('html');
		$this->email->from('rindra.yudha@gmail.com', 'Pisilia Decoration');	// 'prisiliadecoration@gmail.com', 'Prisilia Decoration'
		$this->email->subject($owner->nama . ' - ' . 'Pemberitahun Jadwal Jatuh Tempo (tes email reminder');
		$this->email->to('rindra.yudha@gmail.com');	//$owner->email1
		$this->email->cc('hadikusyanto@gmail.com');	//frankysaputra83@gmail.com

		if ($schedule > 0) {
			$data	= array(
				'company'	=> $owner,
				'schedule'	=> $schedule
			);

			$body	= $this->load->view('invoicing/mail_schedule_invoice.php', $data, TRUE);	// invoicing/mail_schedule_invoice.php
			$this->email->message($body);
			$this->email->set_newline("\r\n");

			if ($this->email->send()) {
				echo "Email Berhasil Terkirim!!";
			} else {
				echo "Email Gagal Terkirim!!";
			}
		} else {
			echo "Tidak ada jadwal invoice besok!!";
		}
	}
}
